### ISSUE TITLE
Splitten: mediziner.json und gesundheit.json

### ISSUE THREAD

**Issue by botic** [botic/seestadt-data#10]
Für eine Aufnahme unter `mediziner.json` wird in Zukunft der Dr. med. das Kriterium sein.

@mtheli: Ich baue das erst am Abend um, bis dahin besser nix machen an den Dateien :wink:

**Comment by mtheli** [comment]
Ok, alles klar. Wird gemacht.

Ja, es ist echt erstaunlich wie viele Psychotherapeuten und Coaches in der Seestadt gibt. 

Die neue Datei für Gesundheit finde ich gut!

**Comment by botic** [comment]
Erledigt.
